eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8763/eureka/,http://127.0.0.1:8762/eureka/
    register-with-eureka: false
  server:
    enable-self-preservation: false
server:
  port: 8761
spring:
  application:
    name: eurekaserver